logging:
  level: INFO
  loggers:
    com.warehouse: DEBUG

swagger:
  resourcePackage: com.warehouse.resources

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: 1234
  url: jdbc:postgresql://localhost:5432/widget-warehouse
  # the SQL query to run when validating a connection's liveness
  validationQuery: "SELECT 1"

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    # This will reset the database every time the app runs, it is like this for simplicity and should be avoided in real life apps
    hibernate.hbm2ddl.auto: create